pipeline {
    agent any

    environment {
        DEPLOY_DIR = '/var/www/auto.jazmincarlos.eu'
        PROJECT_REPO = 'https://github.com/jazmin0618/auto.git'
        PROJECT_DIR = 'reactasir'
    }

    stages {
        stage('Clonar Proyecto') {
            steps {
                echo 'Clonando proyecto de React desde iawasir2.git'
                sh 'rm -rf auto'
                sh "git clone ${env.PROJECT_REPO}"
            }
        }

        stage('Instalar y compilar React') {
            steps {
                dir("iawasir2/${env.PROJECT_DIR}") {
                    echo '📥 Instalando dependencias...'
                    sh 'npm install'

                    echo '🔨 Compilando con Vite (npm run build)...'
                    sh 'npm run build'
                }
            }
        }
    
        stage('Deploy a NGINX') {
            steps {
                echo '🚀 Desplegando contenido a /var/www...'
                script {
                    sh "sudo rm -rf ${env.DEPLOY_DIR}/*"
                    sh "sudo mkdir -p ${env.DEPLOY_DIR}"
                    sh "sudo cp -r iawasir2/${env.PROJECT_DIR}/dist/* ${env.DEPLOY_DIR}/"
                    sh "sudo chown -R www-data:www-data ${env.DEPLOY_DIR}"
                    sh "sudo chmod -R 755 ${env.DEPLOY_DIR}"
                }
            }
        }
    }

    post {
        success {
            echo '✅ ¡Sitio desplegado correctamente!'
        }
        failure {
            echo '❌ Falló el pipeline. Revisa los logs.'
        }
    }
}
