apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: sp-auto
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  type: NodePort
  ports:
    - name: http-port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
