version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080" # Jenkins UI
      - "50000:50000" # Jenkins agent
    volumes:
      - /home/jazmin/jenkins_home:/var/jenkins_home
      - /home/jazmin/.kube:/var/jenkins_home/.kube
      - /home/jazmin/.minikube:/var/jenkins_home/.minikube
      - /var/run/docker.sock:/var/run/docker.sock
