apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: my-app  # Debe coincidir con el label de tus pods
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30090  # Rango válido: 30000-32767